# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632d11e4e497f07aee954d6f20143e70c993fecd6492bc39d2045bd618b3233a161b4607ef6bad910e2301f36395875d5ee35d2031e2b87b43bd5f072081d200

test:
  secret_key_base: 6dfc010b3ffa709e51619536bd4e9ea7f03c05bbe14c8fa69a304033bdaf909d2b51556f31c1b7e5b5ca916cce0f692ab3978fe138729c06693e39fb394a7b4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
